# setup and use a GitHub runner to run unit tests
name: Jest Tests

on:
  [push]
  [pull_request]
  # [merge]

jobs:
  tests:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm clean-install
        run: npm ci
      - name: tests
        run: npm test